language: ruby
rvm:
  - "2.0.0"

bundler_args: --without development production

env:
  global:
    - RAILS_ENV=test

before_script:
  - export CI=true USER=postgres
  - psql -c 'create database destroyer_test' -U postgres
  - RAILS_ENV=test bundle exec rake db:schema:load db:migrate
