development: &dev
  adapter: postgresql
  encoding: unicode
  database: destroyer_development
  pool: 5
  username: <%= ENV['USER'] %>
  password:

test:
  <<: *dev
  database: destroyer_test

production:
  <<: *dev
  database: destroyer_production
